[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["optionsExchange"]
remappings = ["de-test/=lib/ds-test/src/", "@openzeppelin/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config